spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    # ✅ 운영에서는 환경변수로 MySQL 연결
    # ✅ 로컬 개발에서는 H2 DB 기본값 사용
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:create}
    open-in-view: false

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    root: INFO

jwt:
  secret: V2VMa2VTaWdvcm90YWxrQW5kSXRzQmVzdG9mQmVzdFNlY3JldEtleUZvclByb2plY3Q= # <-- 64바이트 이상의 Base64 인코딩된 문자열
  access-token-validity-in-seconds: 86400 # 24시간
  refresh-token-validity-in-seconds: 604800 # 7일