name: CI/CD Pipeline (main only)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      IMAGE_NAME: zerojae175/sigorotalk
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --cache-from=type=registry,ref=${IMAGE_NAME}:cache \
            --cache-to=type=registry,ref=${IMAGE_NAME}:cache,mode=max \
            -f Dockerfile \
            -t ${IMAGE_NAME}:main_${IMAGE_TAG} \
            --push .

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Save SSH Key
        run: |
          echo "${{ secrets.SSH_KEY }}" > /tmp/ssh_key.pem
          chmod 600 /tmp/ssh_key.pem

      - name: Deploy using Docker Compose
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            TAG="main_${{ github.sha }}"
            IMAGE="zerojae175/sigorotalk:$TAG"
            APP_DIR="/home/${{ secrets.SSH_USERNAME }}/sigorotalk"

            echo "📥 Pulling Docker image..."
            docker pull $IMAGE

            echo "📂 Creating application directory if not exists..."
            mkdir -p $APP_DIR

            echo "📄 Generating .env file..."
            echo "IMAGE=$IMAGE" > $APP_DIR/.env
            echo "DB_URL=${{ secrets.DB_URL }}" >> $APP_DIR/.env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $APP_DIR/.env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $APP_DIR/.env
            echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> $APP_DIR/.env

            echo "✅ .env file created at $APP_DIR/.env"

            echo "🚀 Deploying with Docker Compose..."
            cd $APP_DIR
            docker compose down || true
            docker compose up -d --remove-orphans

            echo "🎉 sigorotalk 프로젝트 배포 완료!"
